services:
  api:
    build:
      context: .
      dockerfile: GameOfLife.Api/Dockerfile
    ports:
      - "5168:5168"

  react:
    build:
      context: ./GameOfLife.ReactUI
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: http://localhost:5168/api/game
    ports:
      - "5173:80"
    depends_on:
      - api
